---
title: "econ_assignment4"
author: "Jessica Jagdeo"
date: "May 28, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message = FALSE}

library(tidyverse)

carbon_data <- read_csv("HW4Data.csv")

```

1. Model of marginal cost of abatement for each sector

```{r, visualizing data to find functional form}

# Exploratory Graphs

sector_a <- ggplot(carbon_data, aes(x = Abatement, y = MC_A)) + 
  geom_point()
sector_a
# Looks linear enough...?


sector_b <- ggplot(carbon_data, aes(x = Abatement, y = MC_B)) + 
  geom_point()
sector_b
# idk

sector_c <- ggplot(carbon_data, aes(x = Abatement, y = MC_C)) + 
  geom_point()
sector_c
# Exponential...?

sector_d <- ggplot(carbon_data, aes(x = Abatement, y = MC_D)) + 
  geom_point()
sector_d
#idk 

```

```{r, estimating parameters}

# Linear Regressions

# Sector A

sector_a_model <- lm(MC_A ~ Abatement, data = carbon_data)
sector_a_model

# Cost of carbon abatement = 0.5768*(Abatement) - 8.6445


# Sector B
sector_b_model <- lm(MC_B ~ Abatement, data = carbon_data)
sector_b_model

# Cost of carbon abatement = 0.1987*(Abatement) + 9.3177


# Sector C
sector_c_model <- lm(MC_C ~ Abatement, data = carbon_data)
sector_c_model

# Cost of carbon abatement = 0.7838*(Abatement) - 11.6550


# Sector D
sector_d_model <- lm(MC_D ~ Abatement, data = carbon_data)
sector_d_model

# Cost of abatement = 0.2599*(Abatement) + 9.6875

```

```{r, model fit}

# Detailed model information

# Sector A

summary(sector_a_model)

# R^2 = 0.9104, p for model fit = 1.01e-08

# Basd on this model, Tons of carbon abatement significanly predicts marginal cost of abatement,  R^2 is the proportion of the variance in cost of abatement that is explained by the tons of carbon abatement. 91% of variance in cost is predictable by tons of carbon abatement and 9% of variance in cost is not predictable by tons.


# Sector B
summary(sector_b_model)

# R^2 = 0.5664, p = 0.0007672

# Secctor C
summary(sector_c_model)

# R^2 = 0.8752, p = 1.044e-07

# Sector D
summary(sector_d_model)
# R^2 = 0.5434, p = 0.001121


```

```{r, graphing supply curves}

# Sector A

coeff_a <- coefficients(sector_a_model)
eq_sector_a <- paste0("y = ", coeff_a[2], "*x ", coeff_a[1])

equation_a_supply = function(x) {x*coeff_a[2] + coeff_a[1]}
curve(equation_a_supply, from = 0, to = 300, xlim = c(0,300), xaxs = "i", ylim = c(-10,250), yaxs = "i")


# Add sector B

coeff_b <- coefficients(sector_b_model)
eq_sector_b <- paste0("y = ", coeff_b[2], "*x ", coeff_b[1])

equation_b_supply = function(x) {x*coeff_b[2] + coeff_b[1]}
curve(equation_b_supply, from = 0, to = 300, add = TRUE, col = "blue")


# Add sector C

coeff_c <- coefficients(sector_c_model)
eq_sector_c <- paste0("y = ", coeff_c[2], "*x ", coeff_c[1])

equation_c_supply = function(x) {x*coeff_c[2] + coeff_c[1]}
curve(equation_c_supply, from = 0, to = 300, add = TRUE, col = "green")


# Add sector D

coeff_d <- coefficients(sector_d_model)
eq_sector_d <- paste0("y = ", coeff_d[2], "*x ", coeff_d[1])

equation_d_supply = function(x) {x*coeff_d[2] + coeff_d[1]}
curve(equation_d_supply, from = 0, to = 300, add = TRUE, col = "purple")

```

2. Demand Curve

```{r}

# Find the intersection of the marginal cost curves with current emissions from each sector:


# Sector A

# Cost of carbon abatement = 0.5768*(Abatement) - 8.6445

# Current emissions is 180 tons

0.5768*180-8.6445 # Equals $95.18

# Points: (180, 0) and (0, 95.18)

# Slope: -0.5287778

(95.18-0)/(0-180)

# Y-intercept: 95.18



# Sector B

# Cost of carbon abatement = 0.1987*(Abatement) + 9.3177

# Current emissions are 200 tons

0.1987*200+9.3177 # Equals $49.06

# Points: (200, 0) and (0, 49.06)

# Slope: -0.2453

(49.06-0)/(0-200)

# Y-intercept: 49.06



# Sector C

# Cost of carbon abatement = 0.78388(Abatement) - 11.6550

# Current emissions are 220 tons

0.78388*220-11.6550 # Equals $160.80

# Points: (220, 0) and (0, 160.80)

# Slope: -0.7309091

(160.80-0)/(0-220)

# Y-intercept: 160.80



# Sector D

# Cost of abatement = 0.2599*(Abatement) + 9.6875

# Current emissions are 300 tons

0.2599*300+9.6875 # Equals $87.66

# Points: (300, 0) and (0, 87.66)

# Slope: -0.2922

(87.66-0)/(0-300)

# Y-intercept: 87.66

```

```{r, demand curves}

# Demand curves for each sector:


# Sector A

# y = -0.5287778X + 95.18




# Sector B

# y = -0.2453X + 49.06




# Sector C

# y = -0.7309091X + 160.80




# Sector D

# y =  -0.2922X + 87.66


```

```{r, graphing the demand curves}

# Sector A

slope_a <- -0.5287778
y_int_a <- 95.18

equation_a_demand = function(x) {x*slope_a + y_int_a}
curve(equation_a_demand, from = 0, to = 200, xlim = c(0,300), xaxs = "i", ylim = c(0,200), yaxs = "i")


# Add Sector B 

slope_b <- -0.2453
y_int_b <- 49.06

equation_b_demand = function(x) {x*slope_b + y_int_b}
curve(equation_b_demand, from = 0, to = 300, add = TRUE, col = "blue")


# Add Sector C

slope_c <- -0.7309091
y_int_c <- 160.80

equation_c_demand = function(x) {x*slope_c + y_int_c}
curve(equation_c_demand, from = 0, to = 300, add = TRUE, col = "green")


# Add Sector D

slope_d <- -0.2922
y_int_d <- 87.66

equation_d_demand = function(x) {x*slope_d + y_int_d}
curve(equation_d_demand, from = 0, to = 300, add = TRUE, col = "purple")

```

3. Country X Abatement

a. Cap on carbon

```{r, total cost of meeting target if each county reduces by 100 tons}

# Sector A
# Cost of carbon abatement = 0.5768*(Abatement) - 8.6445
0.5768*(100) - 8.6445
# Cost = $49.0355


# Sector B
# Cost of carbon abatement = 0.1987*(Abatement) + 9.3177
0.1987*(100) + 9.3177
# Cost = $29.1877


# Sector C
# Cost of carbon abatement = 0.7838*(Abatement) - 11.6550
0.7838*(100) - 11.6550
# Cost = 66.725


# Total cost for Country X
49.0355 + 29.1877 + 66.725
# Total cost = $144.9482

```

```{r, cost or benefit to each sector}

# Cost might just be the value above for each sector??

# Sector A: $49.0355
# Sector B: $29.1877
# Sector C: $66.725

```

```{r, tax revenue generated}

# $0 since this is not a tax 

```

b. Tax on Carbon

```{r, add equations horizontally}

# Rearragne equations

# Sector A: Cost of carbon abatement = 0.5768*(Abatement) - 8.6445
# Abatement = 1.733703*(cost) + 14.987
      # non-rounded numbers just in case:
      a1 <- 1/0.5768
      a2 <- 8.6445/0.5768


# Sector B: Cost of carbon abatement = 0.1987*(Abatement) + 9.3177
# Abatement = 5.032713*(cost) -  46.89331
      # non-rounded numbers
      b1 <- 1/0.1987
      b2 <- -9.3177/0.1987


# Sector C: Cost of carbon abatement = 0.7838*(Abatement) - 11.6550
# Abatement = 1.275836*(cost) + 14.86986
      #non-rounded numbers
      c1 <- 1/0.7838
      c2 <- 11.6550/0.7838


# Add them up for aggregate equation
      
# Abatement = (a1 + b1 + c1)*cost + (a2 + b2 + c2)
      (a1 + b1 + c1) # 8.042251
      (a2 + b2 + c2) # -17.03644
# Abatenent = 8.042251*(cost) - 17.03644

```
